services:

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      DATABASE_URL: "mysql://yahtzee:password@database:3306/yahtzee?serverVersion=8.0.32&charset=utf8mb4"
    ports:
      - '8080:80'
    volumes:
      - ./api:/var/www/app
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped

  cache:
    image: redis:7.0.15-alpine
    ports:
      - '16379:6379'
    volumes:
      - cache_data:/data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning --requirepass yahtzee_cache --maxmemory 412M

  database:
    image: mysql:8.0.37
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yahtzee
      MYSQL_USER: yahtzee
      MYSQL_PASSWORD: password
    ports:
      - '13306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped

volumes:
  cache_data:
  mysql_data: