services:

  api:
    container_name: api
    build: docker/api
    ports:
      - '8080:80'
    volumes:
      - ./api:/var/www/api
      - ./docker/api/entrypoint.sh:/etc/entrypoint.sh
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped

  cache:
    container_name: cache
    image: redis:7.0.15-alpine
    ports:
      - '16379:6379'
    volumes:
      - cache_data:/data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning --requirepass yahtzee_cache --maxmemory 412M

  database:
    container_name: database
    image: mysql:8.0.37
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yahtzee
      MYSQL_USER: yahtzee
      MYSQL_PASSWORD: password
    ports:
      - '13306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped

volumes:
  cache_data:
  mysql_data: