nelmio_api_doc:
    use_validation_groups: true
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api/v1/
            documentation:
                info:
                    title: Yahtzee Default API
                    description: An API that allows for Yahtzee games
                    version: 1.0.0

    documentation:
        servers:
            - url: http://localhost:8080/
              description: Development server
            - url: https://yahtzee.herc.work/
              description: Production server

        components:
            securitySchemes:
                app-secret:
                    type: apiKey
                    in: header
                    name: App-Secret
                    description: "The authorized APP secret of your application"
