nelmio_api_doc:
    use_validation_groups: true
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api/v1/
            documentation:
                info:
                    title: Yahtzee Default API
                    description: An API that allows for Yahtzee games
                    version: 1.0.0
