kind: pipeline
name: default

steps:
  - name: install
    image: composer
    commands:
      - composer install

  - name: php-unit
    image: php:8
    commands:
      - api/bin/phpunit api/tests/unit/

  - name: php-spec
    image: php:8
    commands:
      - api/bin/phpspec run