kind: pipeline
name: default
type: docker

steps:
  - name: install-app
    image: composer
    commands:
      - cd api
      - composer install

  - name: install-tools
    image: composer
    commands:
      - cd tools/php-cs-fixer
      - composer install
    depends_on:
      - install-app
    when:
      event:
        - push
        - custom

  - name: php-cs-fixer
    image: php:8
    commands:
      - php tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --diff api/src
    depends_on:
      - install-app
      - install-tools
    when:
      event:
        - push
        - custom

  - name: php-unit
    image: php:8
    commands:
      - php api/bin/phpunit api/tests/unit/
    depends_on:
      - install-app
      - install-tools
    when:
      event:
        - push
        - custom

  - name: php-spec
    image: php:8
    commands:
      - php api/bin/phpspec run
    depends_on:
      - install-app
      - install-tools
    when:
      event:
        - push
        - custom

  - name: build-push
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      repo: vladerc/yahtzee-api
      tags:
        - "dev"
        - "${DRONE_COMMIT_SHA:0:8}"
      dockerfile: docker/api/Dockerfile
    depends_on:
      - php-cs-fixer
      - php-unit
      - php-spec
    when:
      event:
        - push
        - custom

  - name: build-tag
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      repo: vladerc/yahtzee-api
      tags:
        - "latest"
        - "stable"
        - "${DRONE_COMMIT_SHA:0:8}"
        - "${DRONE_TAG}"
      dockerfile: docker/api/Dockerfile
    depends_on:
      - install-app
    when:
      event: tag